#include "ofMain.h"

class Term{
/*
* for term generated by collatz rule
*/
public:
    Term();
    Term(int n);
    
    int number;
    int next_number;
    int level;
    
    glm::vec3 pos;
    
    vector<int> prevTerms;
};
